/**
 * New node file
 */
const MAX_BUFFER_SIZE=512;

const REQUEST_FILE = 0x01;
const RESPONSE_FILE = 0x02;
const COMBI_FILE = 0x03;

const OPEN_REQUEST=0x00000100;
const OPEN_RESPONSE=0x00000101;
const CLOSE_REQUEST=0x00000200;
const CLOSE_RESPONSE=0x00000201;
const GET_PROFILE_PACK_REQUEST=0x00000300;
const GET_PROFILE_PACK_RESPONSE=0x00000301;
const GET_PROFILE_LIST_REQUEST=0x00000400;
const GET_PROFILE_LIST_RESPONSE=0x00000401;
const GET_PROC_PARAMETER_REQUEST=0x00000500;
const GET_PROC_PARAMETER_RESPONSE=0x00000501;
const SET_PROC_PARAMETER_REQUEST=0x00000600;
const SET_PROC_PARAMETER_RESPONSE=0x00000601;
const GET_LIST_REQUEST=0x00000700;
const GET_LIST_RESPONSE=0x00000701;
const ATTENTION_RESPONSE=0x0000FF01;

const UNSIGNED = 0x06;
const INTEGER = 0x05;
const BOOLEAN = 0x04;
const OCTET_STRING = 0x00;

module.exports = {
	OPEN_REQUEST: OPEN_REQUEST,
	OPEN_RESPONSE: OPEN_RESPONSE,
	CLOSE_REQUEST: CLOSE_REQUEST,
	CLOSE_RESPONSE: CLOSE_RESPONSE,
	GET_PROFILE_PACK_REQUEST: GET_PROFILE_PACK_REQUEST,
	GET_PROFILE_PACK_RESPONSE: GET_PROFILE_PACK_RESPONSE,
	GET_PROFILE_LIST_REQUEST: GET_PROFILE_LIST_REQUEST,
	GET_PROFILE_LIST_RESPONSE: GET_PROFILE_LIST_RESPONSE,
	GET_PROC_PARAMETER_REQUEST: GET_PROC_PARAMETER_REQUEST,
	GET_PROC_PARAMETER_RESPONSE: GET_PROC_PARAMETER_RESPONSE,
	SET_PROC_PARAMETER_REQUEST: SET_PROC_PARAMETER_REQUEST,
	SET_PROC_PARAMETER_RESPONSE: SET_PROC_PARAMETER_RESPONSE,
	GET_LIST_REQUEST: GET_LIST_REQUEST,
	GET_LIST_RESPONSE: GET_LIST_RESPONSE,
	ATTENTION_RESPONSE: ATTENTION_RESPONSE,
	UNSIGNED: UNSIGNED,
	INTEGER: INTEGER,
	BOOLEAN: BOOLEAN,
	OCTET_STRING: OCTET_STRING
};